name: iOS CI (Xcode build)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-ios:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode.app

      - name: Resolve Swift Packages
        run: |
          xcodebuild -resolvePackageDependencies \
            -project Adapt/Adapt.xcodeproj \
            -scheme Adapt

      - name: Build (iOS Simulator)
        run: |
          xcodebuild \
            -project Adapt/Adapt.xcodeproj \
            -scheme Adapt \
            -sdk iphonesimulator \
            -configuration Debug \
            -destination 'platform=iOS Simulator,name=iPhone 15' \
            build | xcpretty
        env:
          NSUnbufferedIO: "YES"
        shell: bash


